chore: Dockerfile and script cleanup

diff --git a/.github/workflows/ash-image-build.yml b/.github/workflows/ash-image-build.yml
--- a/.github/workflows/ash-image-build.yml
+++ b/.github/workflows/ash-image-build.yml
@@ -43,17 +43,39 @@ jobs:
 
       - name: Run ASH against itself
         run: |-
-          # Create the ash_output directory
+          # Create the ash_output directory if it doesn't exist
           mkdir -p ash_output
 
-          # Run ASH against the itself
+          # Enable errexit and print commands as they are run
           set +e
+          # Set the exit code to 0 by default
           EXIT_CODE=0
 
-          docker run \
-            --platform linux/amd64 \
-            --mount type=bind,source="$(pwd)",destination=/src,readonly \
-            --mount type=bind,source="$(pwd)/ash_output",destination=/out \
-            --tmpfs /run/scan/src:rw,noexec,nosuid \
-            ${{ env.IMG_NAME }} \
-            ash --source-dir /src --output-dir /out || EXIT_CODE=1
+          # Run ASH against itself
+          {
+            docker run \
+              --platform linux/amd64 \
+              --mount type=bind,source="$(pwd)",destination=/src,readonly \
+              --mount type=bind,source="$(pwd)/ash_output",destination=/out \
+              --tmpfs /run/scan/src:rw,noexec,nosuid \
+              ${{ env.IMG_NAME }}  \
+              ash --source-dir /src --output-dir /out | tee ash_output/ash_stdout.txt
+          } || EXIT_CODE=1
+
+          if [[ "${EXIT_CODE}" != "0" ]]; then
+            cat ash_output/aggregated_results.txt
+          fi
+          echo "EXIT_CODE $EXIT_CODE"
+
+      - name: Collect ash_stdout.txt
+        uses: actions/upload-artifact@v2
+        with:
+          name: ash_stdout
+          path: ash_output/ash_stdout.txt
+
+      - name: Collect aggregated_results.txt
+        uses: actions/upload-artifact@v2
+        with:
+          name: aggregated_results
+          path: ash_output/aggregated_results.txt
+          if-no-files-found: error
