feat(ci): added pytest invocation to workflow

diff --git a/.github/workflows/ash-build-and-scan.yml b/.github/workflows/ash-build-and-scan.yml
--- a/.github/workflows/ash-build-and-scan.yml
+++ b/.github/workflows/ash-build-and-scan.yml
@@ -174,6 +174,48 @@ jobs:
           path: ash_output
           if-no-files-found: error
 
+  unit-test:
+    name: Run unit tests
+    needs: []
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python3 -
+          echo "$HOME/.local/bin" >> $GITHUB_PATH
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          cache: 'poetry'
+
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python3 -
+          echo "$HOME/.local/bin" >> $GITHUB_PATH
+          poetry config virtualenvs.create true
+          poetry config virtualenvs.in-project true
+
+      - name: Install dependencies
+        run: poetry install
+
+      - name: Run PyTest
+        run: poetry run pytest
+
+      - name: Publish PyTest JUnit Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        continue-on-error: true
+        with:
+          report_paths: '**/pytest.junit.xml'
+          include_passed: true
+
+
   build-docs:
     name: Build documentation
     needs: []
